server:
  port: 8011
spring:
  application:
    name: business-travel
  datasource:
    url: jdbc:mysql://localhost:3306/business_travel?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 96MATING
    test-on-borrow: false
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    time-between-eviction-runs-millis: 600000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl